language: python

python:
    - "2.7"

cache: pip


before_install:
    # This is needed for the SSH tests (being able to ssh to localhost)
    # And will also be used for the docker test
    - cd make_ghpages

install:
    # Install needed dependencies
    - pip install -r requirements.txt

script: ./make_pages.py

# See docs here: https://docs.travis-ci.com/user/deployment/pages/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
  target_branch: gh-pages
  local_dir: out

git:
  depth: 3